# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87797642f2ddd167b6a6081eab99a6c0b494554bfafd5490f6c265dfefaff119e30ba2daad683020c47a1ab9479edf5714a82f979a0e5d0d4291c4cca8a67b0

test:
  secret_key_base: e3c5fb782d6c7aed0924f00c0a3deb75ec3c77fb6a5093354407d9ab06be2f10a6d8f2a7324767275e081fe76516c61f1b4cd4b218c5ee07ff44ec3644acbf8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
